---
dist: trusty
language: node_js
node_js:
- 8
- 10
cache:
  yarn: true
  directories:
  - .npm
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --nightly
- export PATH="$HOME/.yarn/bin:$PATH"
install: true
after_success:
- yarn install
- cd packages/react-mdc
- yarn test
